In [1]:
!pip install facenet_pytorch
!wget https://github.com/yokahealthcare/C-Eyes-App-New/raw/master/video.mp4

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 10.2 MB/s eta 0:00:00
--2023-08-11 09:57:31--  https://github.com/yokahealthcare/C-Eyes-App-New/raw/master/video.mp4
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/yokahealthcare/C-Eyes-App-New/master/video.mp4 [following]
--2023-08-11 09:57:32--  https://raw.githubusercontent.com/yokahealthcare/C-Eyes-App-New/master/video.mp4
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6961155 (6.6M) [application/octet-stream]
Saving to: ‘video.mp4’

video.mp4           100%[===================>]   6.64M  --.-KB/s    in 0.05s   

2023-08-11 09:57

In [6]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.4/195.4 MB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 48.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 51.2 MB/s eta 0:00:00


In [1]:
!pip list | grep "torch"

facenet-pytorch    2.5.3
torch              2.0.1+cpu
torchvision        0.15.2+cpu


In [2]:
from facenet_pytorch import MTCNN
from PIL import Image
import torch
import cv2
import numpy as np
#from google.colab.patches import cv2_imshow

# colors
GREEN = (0, 255, 0)
RED = (0, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device being used : {device}")

# write a video
# Define the codec and create a VideoWriter object
#fourcc = cv2.VideoWriter_fourcc(*'XVID')  # Codec for AVI format
#out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640, 480))  # Change resolution as needed

# Create face detector
mtcnn = MTCNN(keep_all=True, device=device)

cap = cv2.VideoCapture("video.mp4")

# Check if the video file was opened successfully
if not cap.isOpened():
    print("Error: Could not open video file.")
    exit()

while cap.isOpened():

    success, ori_frame = cap.read()
    if not success:
        print("Video has ended!")
        break

    frame = cv2.cvtColor(ori_frame, cv2.COLOR_BGR2RGB)
    frame = Image.fromarray(frame)

    # Detect face
    boxes, probs, landmarks = mtcnn.detect(frame, landmarks=True)



    # Convert the OpenCV image to a torch.Tensor
    # Convert the image from BGR to RGB format
    # frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    # Convert to torch.Tensor with shape (C, H, W)
    # frame_tensor = torch.from_numpy(frame_rgb.transpose((2, 0, 1))).float()

    # print(f"frame : {frame}")

    # boxes, probs, landmarks = mtcnn.detect(frame_tensor, landmarks=True)

    # faces = []

    # box_ind = int(i / self.stride)
    # if boxes[box_ind] is None:
    #     continue
    # for box in boxes[box_ind]:
    #     box = [int(b) for b in box]

    print(f"Boxes : {boxes}")
#     if boxes is not None:
#       for box in boxes:
#           #convert to int
#           box = [int(x) for x in box]
#           x_l, y_l, x_r, y_r = box
#           cv2.rectangle(ori_frame, (x_l, y_l), (x_r, y_r), GREEN, 2)

      # Write the frame to the output video
      # out.write(ori_frame)
      # cv2_imshow(ori_frame)


    #cv2.imshow("frame", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
#out.release()
cv2.destroyAllWindows()

Device being used : cpu
Boxes : [[141.9693603515625 109.20816040039062 163.123046875 138.34886169433594]]
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : [[155.49160766601562 179.83453369140625 195.6802520751953
  238.13796997070312]]
Boxes : None
Boxes : [[164.9314422607422 99.28191375732422 189.392822265625 134.1432647705078]]
Boxes : [[165.48272705078125 98.84481811523438 189.9856414794922
  132.89959716796875]]
Boxes : [[144.1433563232422 178.9849395751953 191.1802978515625
  240.00015258789062]]
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : [[176.17739868164062 94.0255355834961 204.00112915039062
  131.40567016601562]]
Boxes : [[176.17730712890625 94.02651977539062 204.0008087158203
  131.40542602539062]]
Boxes :

Boxes : [[269.13800048828125 101.23405456542969 326.52593994140625
  168.53236389160156]]
Boxes : [[269.13800048828125 101.23405456542969 326.52593994140625
  168.53236389160156]]
Boxes : [[268.9247131347656 99.79752349853516 326.6330261230469 167.1305389404297]]
Boxes : [[269.48187255859375 98.56495666503906 327.0860290527344
  165.8118133544922]]
Boxes : [[268.9217224121094 98.22355651855469 327.8995056152344 167.8068084716797]]
Boxes : [[268.470947265625 97.99919891357422 327.5191955566406 167.0515594482422]]
Boxes : [[268.3357238769531 97.86646270751953 327.5464172363281 167.1209716796875]]
Boxes : [[267.656982421875 96.62765502929688 325.8180236816406 165.06373596191406]]
Boxes : [[266.95111083984375 95.25370788574219 325.6574401855469
  163.71975708007812]]
Boxes : [[266.34295654296875 94.31193542480469 325.23614501953125
  164.4230194091797]]
Boxes : [[265.0090026855469 96.19886016845703 321.68621826171875
  162.78977966308594]]
Boxes : [[265.00921630859375 96.19749450683594 321

Boxes : [[240.96026611328125 103.05084228515625 358.67816162109375
  254.20399475097656]]
Boxes : [[241.89295959472656 103.20813751220703 359.5155944824219
  254.78140258789062]]
Boxes : [[240.79432678222656 102.49124908447266 359.51751708984375
  254.8540496826172]]
Boxes : [[237.93392944335938 95.72531127929688 362.2033996582031
  253.97837829589844]]
Boxes : [[242.10643005371094 105.97468566894531 359.20758056640625
  254.0286102294922]]
Boxes : [[242.8778839111328 107.1335678100586 358.8258056640625 254.2461700439453]]
Boxes : [[244.3040008544922 108.29159545898438 358.62811279296875
  254.568603515625]]
Boxes : [[243.37989807128906 107.2103500366211 358.981201171875 254.1448211669922]]
Boxes : [[241.54859924316406 98.98824310302734 360.9544982910156
  254.64117431640625]]
Boxes : [[242.67681884765625 103.04885864257812 362.4915466308594
  256.44232177734375]]
Boxes : [[240.80279541015625 98.7874526977539 363.71160888671875
  257.0646667480469]]
Boxes : [[241.37985229492188 99.5788

Boxes : [[343.3502197265625 85.44422912597656 472.0315246582031
  242.33477783203125]]
Boxes : [[343.23773193359375 84.9717788696289 472.8009948730469 241.9949951171875]]
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : None
Boxes : No

Boxes : [[212.7252960205078 127.75847625732422 295.66888427734375
  240.44821166992188]
 [342.4810485839844 92.36080932617188 428.25823974609375
  192.0819854736328]]
Boxes : [[213.0793914794922 126.87771606445312 298.3132019042969
  243.14804077148438]
 [346.308837890625 94.06768035888672 429.2115478515625 192.9369354248047]]
Boxes : [[212.96435546875 126.95718383789062 298.1567687988281 243.186279296875]
 [347.1099548339844 94.41985321044922 429.24102783203125
  192.4605712890625]]
Boxes : [[213.80770874023438 127.97301483154297 299.83575439453125
  246.0026397705078]
 [347.8985290527344 94.84532165527344 432.5001525878906 196.5817413330078]]
Boxes : [[221.70291137695312 134.40548706054688 304.1163330078125 245.13720703125]
 [351.3606872558594 97.03506469726562 433.4872131347656 198.6912384033203]]
Boxes : [[222.54367065429688 133.69708251953125 308.6986389160156
  249.3079833984375]
 [347.5820617675781 96.8834457397461 433.496337890625 199.2928924560547]]
Boxes : [[223.6963806152343

Boxes : [[300.318603515625 84.25208282470703 454.809326171875 275.3401794433594]]
Boxes : [[301.725830078125 86.50787353515625 454.54974365234375 275.1651611328125]]
Boxes : [[301.3904724121094 85.45614624023438 456.45574951171875
  277.68939208984375]]
Boxes : [[303.4114990234375 89.45685577392578 457.583251953125 282.2578430175781]]
Boxes : [[303.4144287109375 89.45836639404297 457.583984375 282.25628662109375]]
Boxes : [[304.4978332519531 94.22120666503906 459.4791259765625
  289.21514892578125]]
Boxes : [[309.18365478515625 99.48805236816406 464.7063903808594
  291.3743896484375]]
Boxes : [[314.1595764160156 105.10313415527344 464.17938232421875
  291.4429016113281]]
Boxes : [[312.0107727050781 108.80297088623047 465.87872314453125
  301.2799072265625]]
Boxes : [[313.3239440917969 108.46627807617188 466.6048889160156
  299.72711181640625]]
Boxes : [[314.1159362792969 114.02416229248047 470.37408447265625
  306.546142578125]]
Boxes : [[315.29193115234375 117.93334197998047 477.04211

KeyboardInterrupt: 

In [ ]:
from facenet_pytorch import MTCNN
from PIL import Image
import torch
from imutils.video import FileVideoStream
import cv2
import time
import glob

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
filenames = "video.mp4"

In [ ]:
class FastMTCNN(object):
    """Fast MTCNN implementation."""

    def __init__(self, stride, resize=1, *args, **kwargs):
        """Constructor for FastMTCNN class.

        Arguments:
            stride (int): The detection stride. Faces will be detected every `stride` frames
                and remembered for `stride-1` frames.

        Keyword arguments:
            resize (float): Fractional frame scaling. [default: {1}]
            *args: Arguments to pass to the MTCNN constructor. See help(MTCNN).
            **kwargs: Keyword arguments to pass to the MTCNN constructor. See help(MTCNN).
        """
        self.stride = stride
        self.resize = resize
        self.mtcnn = MTCNN(*args, **kwargs)

    def __call__(self, frames):
        """Detect faces in frames using strided MTCNN."""
        if self.resize != 1:
            frames = [
                cv2.resize(f, (int(f.shape[1] * self.resize), int(f.shape[0] * self.resize)))
                    for f in frames
            ]

        boxes, probs = self.mtcnn.detect(frames[::self.stride])

        faces = []
        for i, frame in enumerate(frames):
            box_ind = int(i / self.stride)
            if boxes[box_ind] is None:
                continue
            for box in boxes[box_ind]:
                box = [int(b) for b in box]
                faces.append(frame[box[1]:box[3], box[0]:box[2]])

        return faces

In [ ]:
fast_mtcnn = FastMTCNN(
    stride=4,
    resize=1,
    margin=14,
    factor=0.6,
    keep_all=True,
    device=device
)

In [ ]:
def run_detection(fast_mtcnn, filenames):
    frames = []
    frames_processed = 0
    faces_detected = 0
    batch_size = 60
    start = time.time()

    v_cap = FileVideoStream(filenames).start()
    v_len = int(v_cap.stream.get(cv2.CAP_PROP_FRAME_COUNT))

    for j in range(v_len):

        frame = v_cap.read()
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame)

        if len(frames) >= batch_size or j == v_len - 1:

            faces = fast_mtcnn(frames)

            frames_processed += len(frames)
            faces_detected += len(faces)
            frames = []

            print(
                f'Frames per second: {frames_processed / (time.time() - start):.3f},',
                f'faces detected: {faces_detected}\r',
                end=''
            )

    v_cap.stop()

print("Starting...")
run_detection(fast_mtcnn, filenames)